site_name: Thinking

theme: 
     name: mkdocs
    

nav: 
   - Home : index.md
   - English :
      - Synonyms.md
      
   - Apptitude :


extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js